<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="4" failures="1" disabled="0" errors="0" time="0.003" name="AllTests">
  <testsuite name="add" tests="4" failures="1" disabled="0" errors="0" time="0.001">
    <testcase name="normal" status="run" time="0" classname="add" />
    <testcase name="hihih" status="run" time="0" classname="add" />
    <testcase name="test1" status="run" time="0" classname="add" />
    <testcase name="test2" status="run" time="0.001" classname="add">
      <failure message="Value of: add(2, 3)&#x0A;  Actual: 5&#x0A;Expected: 6" type=""><![CDATA[./unittest.cpp:22
Value of: add(2, 3)
  Actual: 5
Expected: 6]]></failure>
    </testcase>
  </testsuite>
</testsuites>
